
services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["/app/docker/entrypoint.sh"]
    ports: 
      - "8080:8000"
  test:
    build: .
    volumes:
      - .:/app
    command: vendor/bin/phpunit